"""Add enabled field to n8n_instances

Revision ID: 58bf1d9670e3
Revises: 5a432502476d
Create Date: 2025-11-10 22:44:14.896384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bf1d9670e3'
down_revision = '5a432502476d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('n8n_instances', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('n8n_instances', 'enabled')
    # ### end Alembic commands ###

